In [3]:
import numpy as np

#np.arrange(起始數,幾個數字，公差，型態) 
#型態:signed整數int8-int64  unsigned整數uint8-uint64 浮點數 float16-128 布林值	bool
#arrange()有時候有結束值有時沒有
#a = np.arange(0,21,step=1,dtype='int64')
#a=np.linspace(0,20,num=20,endpoint=True,retstep=True,dtype='int64')
#所以用linspace比較好

first = np.linspace(0,20,num=20,dtype=int)

print(first)
print("偶數:")
print(first[first%2==0])
print("3的倍數:")
print(first[first%3==0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20]
偶數:
[ 0  2  4  6  8 10 12 14 16 18 20]
3的倍數:
[ 0  3  6  9 12 15 18]
